using Microsoft.EntityFrameworkCore.Migrations;

namespace flash_card.data.Migrations
{
    public partial class AutoGeneratedId : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {

        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {

        }
    }
}
